#Requires -Version 5.1
# Merge category visuals into live published bundle and re-publish (safe for existing groups).
# icon_url: cdn when DNS ready (scripts/setup-cdn.ps1); until then staging-api mirror.
param(
    [int]$FromVersion = 15,
    [string]$Notes = "category visuals pilot"
)

$ErrorActionPreference = "Stop"
$useCdn = $env:USE_CDN_ICON_URLS -eq '1'
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root
. (Join-Path $PSScriptRoot "_env.ps1")
. (Join-Path $PSScriptRoot "_staging-http.ps1")
. (Join-Path $PSScriptRoot "_python.ps1")
Load-ScriptEnv

$stagingHost = ([Uri]$env:STAGING_API_URL.TrimEnd('/')).Host
$seed = Get-Content -Raw -Encoding UTF8 (Join-Path $Root "seed\full-catalog.json") | ConvertFrom-Json
$visualById = @{}
foreach ($c in $seed.categories) {
    if ($c.icon_url) {
        $iconUrl = if ($useCdn) { $c.icon_url } else {
            $c.icon_url -replace 'https://cdn\.alicecommands\.ru', "https://$stagingHost"
        }
        $visualById[$c.id] = @{
            icon_key = $c.icon_key
            icon_url = $iconUrl
            accent_color = $c.accent_color
            accent_color_dark = $c.accent_color_dark
        }
    }
}

$visualMapPath = Join-Path $Root "content\visuals_map.json"
$groupVisualById = @{}
if (Test-Path $visualMapPath) {
    $visualMap = Get-Content -Raw -Encoding UTF8 $visualMapPath | ConvertFrom-Json
    foreach ($prop in $visualMap.groups.PSObject.Properties) {
        $slug = $prop.Value
        $iconUrl = if ($useCdn) { "https://cdn.alicecommands.ru/icons/v1/$slug.svg" } else { "https://$stagingHost/icons/v1/$slug.svg" }
        $groupVisualById[$prop.Name] = @{ icon_key = $slug; icon_url = $iconUrl }
    }
}

$gzipPath = Join-Path $env:TEMP "alice-live-v$FromVersion.json.gz"
$jsonPath = Join-Path $env:TEMP "alice-live-v$FromVersion.json"
$outPath = Join-Path $env:TEMP "alice-visuals-merge.json"

try {
    Invoke-StagingDownload -Path "/v1/content/bundle-backup/content_v$FromVersion.json.gz" -OutFile $gzipPath
    Invoke-PythonCode -Code "import gzip,sys; open(sys.argv[1],'wb').write(gzip.open(sys.argv[2],'rb').read())" $jsonPath $gzipPath

    $bundle = Get-Content -Raw -Encoding UTF8 $jsonPath | ConvertFrom-Json
    foreach ($cat in $bundle.categories) {
        $v = $visualById[$cat.id]
        if ($v) {
            $cat | Add-Member -NotePropertyName icon_url -NotePropertyValue $v.icon_url -Force
            $cat | Add-Member -NotePropertyName accent_color -NotePropertyValue $v.accent_color -Force
            $cat | Add-Member -NotePropertyName accent_color_dark -NotePropertyValue $v.accent_color_dark -Force
            if ($v.icon_key) { $cat.icon_key = $v.icon_key }
        }
    }
    # Group visuals from content/visuals_map.json (generated by tools/content/icon_sync.py)
    foreach ($g in $bundle.command_groups) {
        $v = $groupVisualById[$g.id]
        if ($v) {
            $g | Add-Member -NotePropertyName icon_url -NotePropertyValue $v.icon_url -Force
            $g | Add-Member -NotePropertyName icon_key -NotePropertyValue $v.icon_key -Force
        }
    }

    [IO.File]::WriteAllText($outPath, ($bundle | ConvertTo-Json -Depth 30 -Compress), [Text.UTF8Encoding]::new($false))

    $cookieJar = Join-Path $env:TEMP "alice-visuals-merge-cookies.txt"
    Remove-Item $cookieJar -Force -ErrorAction SilentlyContinue
    New-StagingSession -CookieJar $cookieJar

    Write-Host "Import merged bundle (replace from v$FromVersion + visuals)..."
    Invoke-StagingJsonPost -Path '/admin/api/import/json?mode=replace' -CookieJar $cookieJar -BodyPath $outPath | Out-Null

    Write-Host "Publishing..."
    $publishBody = @{ notes = $Notes; min_app_version = "1.0" } | ConvertTo-Json -Compress
    $result = Invoke-StagingJsonPost -Path '/admin/api/publish' -CookieJar $cookieJar -BodyInline $publishBody
    Write-Host "Published content_version=$($result.contentVersion)"

    $manifest = Invoke-StagingJsonGet -Path '/v1/content/manifest'
    Write-Host "Live: v$($manifest.content_version)"

    # Spot-check music category in bundle
    $py = @"
import gzip,json,sys,urllib.request
m=json.load(urllib.request.urlopen('$($env:STAGING_API_URL)/v1/content/manifest'))
import ssl; ctx=ssl.create_default_context()
b=gzip.decompress(urllib.request.urlopen(m['backup_url'], context=ctx).read())
data=json.loads(b)
for c in data['categories']:
    if c['id'] in ('music','smart_home','timers','kids','tv_video'):
        print(c['id'], c.get('icon_url',''), c.get('accent_color',''))
"@
    Invoke-PythonCode -Code $py
} finally {
    Remove-Item $gzipPath,$jsonPath,$outPath -Force -ErrorAction SilentlyContinue
}

Write-Host "Done."
